name: pull_request

on:
  pull_request:
    branches:
    - "*"

jobs:
  test:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        python:
          - 2.7
          - 3.7

    steps:
    - uses: actions/checkout@v1
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install deps
      run: PYTHON_VERSION=${{ matrix.python }} make install
    - name: Run tests
      run: PYTHON_VERSION=${{ matrix.python }} make test

  lint:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        python:
          - 2.7
          - 3.7

    steps:
    - uses: actions/checkout@v1
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install deps
      run: PYTHON_VERSION=${{ matrix.python }} make install
    - name: Run linters
      run: PYTHON_VERSION=${{ matrix.python }} make lint
    - name: Check package
      run: PYTHON_VERSION=${{ matrix.python }} make check-package
